export enum ActionType {
  SET_USER = "SET_USER",
  SET_PRODUCTS = "SET_PRODUCTS",
  SET_PRODUCT = "SET_PRODUCT",
  SET_PRODUCTS_LOADING_ON = "SET_PRODUCTS_LOADING_ON",
  SET_PRODUCTS_LOADING_OFF = "SET_PRODUCTS_LOADING_OFF",
  SET_IS_LOGGED_TRUE = "SET_IS_LOGGED_TRUE",
  SET_IS_LOGGED_FALSE = "SET_IS_LOGGED_FALSE",
  SET_ORDERS = "SET_ORDERS",
  SET_ORDER = "SET_ORDER",
}
